shops = [
    {"id": "lavkadrugoesoznanie", "name": "Лавка 'Другое сознание'", "goods": []},
    {"id": "lovestore", "name": "Love Store", "goods": []},
    {"id": "stuffman", "name": "Stuffman", "goods": []},
    {"id": "cumrossiitop1cocaine", "name": "[ЦУМ России] TOP 1 COCAINE", "goods": []},
    {"id": "pavstanciya", "name": "ПАВстанция", "goods": []},
    {"id": "conglomerate", "name": "CONGLOMERATE", "goods": []},
    {"id": "yula", "name": "Юла", "goods": []},
    {"id": "7upmarket", "name": "7up market", "goods": []},
    {"id": "sayonara", "name": "Sayonara", "goods": []},
    {"id": "broker", "name": "БРОКЕР", "goods": []},
    {"id": "makedonsky", "name": "Makedonsky", "goods": []},
    {"id": "nostradamus", "name": "Nostradamus", "goods": []},
    {"id": "nacionalnystandart", "name": "Национальный стандарт", "goods": []},
    {"id": "ulyudochki", "name": "у Людочки", "goods": []},
    {"id": "staffberries", "name": "StaffBerries", "goods": []},
    {"id": "solevayakhata", "name": "Солевая Хата", "goods": []},
    {"id": "yamakasi", "name": "YAMAKASI", "goods": []},
    {"id": "stolichny", "name": "Столичный", "goods": []},
    {"id": "briz", "name": "✨Бриз✨", "goods": []},
    {"id": "imperiyasoblazna", "name": "Империя Соблазна", "goods": []},
    {"id": "tretiyrim", "name": "Третий Рим", "goods": []},
    {"id": "link", "name": "Link", "goods": []},
    {"id": "benjamin", "name": "BENJAMIN", "goods": []},
    {"id": "gangbangshop", "name": "GangBang Shop", "goods": []},
    {"id": "cherkizon", "name": "Черкизон", "goods": []},
    {"id": "burgerking", "name": "Burger King", "goods": []},
    {"id": "dendi", "name": "DENDI", "goods": []},
    {"id": "sekretyscha", "name": "Секреты Счастья", "goods": []},
    {"id": "karabas", "name": "Карабас", "goods": []},
    {"id": "ninga", "name": "Ninga", "goods": []},
    {"id": "bigmind", "name": "Big Mind", "goods": []},
    {"id": "loveinside", "name": "Love Inside", "goods": []},
    {"id": "chistotaiuyut", "name": "Чистота и Уют", "goods": []},
    {"id": "moskva_shop", "name": "Москва ГлавШоп", "goods": []},
    {"id": "sanktpeterburg_shop", "name": "Санкт-Петербург ГлавШоп", "goods": []},
    {"id": "novosibirsk_shop", "name": "Новосибирск ГлавШоп", "goods": []},
    {"id": "ekaterinburg_shop", "name": "Екатеринбург ГлавШоп", "goods": []},
    {"id": "kazan_shop", "name": "Казань ГлавШоп", "goods": []},
    {"id": "nizhnijnovgorod_shop", "name": "Нижний Новгород ГлавШоп", "goods": []},
    {"id": "chelyabinsk_shop", "name": "Челябинск ГлавШоп", "goods": []},
    {"id": "samara_shop", "name": "Самара ГлавШоп", "goods": []},
    {"id": "omsk_shop", "name": "Омск ГлавШоп", "goods": []},
    {"id": "rostovnadonu_shop", "name": "Ростов-на-Дону ГлавШоп", "goods": []},
    {"id": "ufa_shop", "name": "Уфа ГлавШоп", "goods": []},
    {"id": "krasnoyarsk_shop", "name": "Красноярск ГлавШоп", "goods": []},
    {"id": "voronezh_shop", "name": "Воронеж ГлавШоп", "goods": []},
    {"id": "perm_shop", "name": "Пермь ГлавШоп", "goods": []},
    {"id": "volgograd_shop", "name": "Волгоград ГлавШоп", "goods": []},
    {"id": "krasnodar_shop", "name": "Краснодар ГлавШоп", "goods": []},
    {"id": "saratov_shop", "name": "Саратов ГлавШоп", "goods": []},
    {"id": "tyumen_shop", "name": "Тюмень ГлавШоп", "goods": []},
    {"id": "tolyatti_shop", "name": "Тольятти ГлавШоп", "goods": []},
    {"id": "izhevsk_shop", "name": "Ижевск ГлавШоп", "goods": []},
    {"id": "barnaul_shop", "name": "Барнаул ГлавШоп", "goods": []},
    {"id": "ulyanovsk_shop", "name": "Ульяновск ГлавШоп", "goods": []},
    {"id": "irkutsk_shop", "name": "Иркутск ГлавШоп", "goods": []},
    {"id": "khabarovsk_shop", "name": "Хабаровск ГлавШоп", "goods": []},
    {"id": "yaroslavl_shop", "name": "Ярославль ГлавШоп", "goods": []},
    {"id": "vladivostok_shop", "name": "Владивосток ГлавШоп", "goods": []},
    {"id": "makhachkala_shop", "name": "Махачкала ГлавШоп", "goods": []},
    {"id": "tomsk_shop", "name": "Томск ГлавШоп", "goods": []},
    {"id": "orenburg_shop", "name": "Оренбург ГлавШоп", "goods": []},
    {"id": "kemerovo_shop", "name": "Кемерово ГлавШоп", "goods": []},
]



# lavkadrugoesoznanie,lovestore,stuffman,cumrossiitop1cocaine,pavstanciya,conglomerate,yula,7upmarket,sayonara,broker,makedonsky,nostradamus,nacionalnystandart,ulyudochki,
# staffberries,solevayakhata,yamakasi,stolichny,briz,imperiyasoblazna,tretiyrim,link,benjamin,gangbangshop,cherkizon,burgerking,dendi,sekretyscha,
# karabas,ninga,bigmind,loveinside,chistotaiuyut